name: cloudflare-ddns
displayName: Cloudflare-ddns
version: 1.0.0
createdAt: 2025-10-13T00:00:00Z
description: A Helm chart for deploying Cloudflare DDNS configuration
homeURL: https://github.com/ashishpal09/helmchart/blob/master/charts/cloudflare-ddns
keywords:
  - cloudflare
  - ddns
maintainers:
  - name: CloudDrove Team
    email: ashish.pal@clouddrove.com
license: Apache-2.0