name: cloudflare
displayName: Cloudflare
version: 1.0.0
createdAt: 2025-10-13T00:00:00Z
description: A Helm chart for deploying Cloudflare DDNS configuration
homeURL: https://github.com/ashishpal09/helmchart/tree/master/charts/cloudflare
keywords:
  - cloudflare
maintainers:
  - name: CloudDrove Team
    email: ashish.pal@clouddrove.com
license: Apache-2.0

