name: Publish Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.artifacthub-repo.yml'
      - '.github/workflows/publish.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Package Helm charts
        run: |
          mkdir -p packaged
          for dir in charts/*/; do
            helm lint "$dir"
            helm package "$dir" -d packaged/
          done

      - name: Generate Helm repo index
        run: |
          helm repo index packaged --url https://clouddrove.github.io/helmchart
          mv packaged/* .

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
