name: Publish Helm Charts to GitHub Pages

on:
  push:
    branches:
      - feat/github-action
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important for pushing to other branches

      - name: Set up Helm
        uses: actions/setup-helm@v4
        with:
          version: latest

      - name: Package Helm charts
        run: |
          mkdir -p packages
          helm package charts/* -d packages
          helm repo index packages --url https://clouddrove.github.io/helmchart

      - name: Copy Artifact Hub metadata file
        run: cp .artifacthub-repo.yml packages/

      - name: Deploy to gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Fetch gh-pages branch and set up worktree
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git worktree add gh-pages-temp gh-pages

          # Replace contents with newly built charts
          rm -rf gh-pages-temp/*
          cp -r packages/* gh-pages-temp/

          # Commit and push
          cd gh-pages-temp
          git add .
          git commit -m "Publish Helm charts from ${GITHUB_REF_NAME} [skip ci]" || echo "No changes to commit"
          git push origin gh-pages
